wrap_comments = true
comment_width = 120
format_code_in_doc_comments = true
condense_wildcard_suffixes = true
normalize_comments = true
normalize_doc_attributes = true
overflow_delimited_expr = true
reorder_impl_items = true
use_field_init_shorthand = true
imports_granularity = "Crate"
