name: Rust

on:
  push:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: write

jobs:
  build-wasm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - uses: Swatinem/rust-cache@v2

      - name: Install Trunk
        run: wget -qO- https://github.com/thedodd/trunk/releases/latest/download/trunk-x86_64-unknown-linux-gnu.tar.gz | tar -xzf-

      - name: Build WASM
        run: ./trunk build --release --public-url "${GITHUB_REPOSITORY#*/}"

  build-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2

      - name: Build Server
        run: cargo build --release --no-default-features --target-dir target/server --verbose
